apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: workloads
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
commonLabels:
  app: test-svc
  backstage.io/kubernetes-id: test-svc
images:
- name: to-be-replaced
  newName: ealen/echo-server
  newTag: latest